# Site-level
description: wolgwang's Explorings of The Deep
livereload: true

# front matter defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

permalink: pretty

# Settings to tweak generation, features, plug-ins
highlighter: rouge
markdown: kramdown
kramdown:
  input:                GFM
  hard_wrap:            false
  smart_quotes:         ["apos", "apos", "quot", "quot"]
  syntax_highlighter:   rouge
  syntax_highligher_opts:
    default_lang: c

# blacklist files/folders to never publish
# Note: declaring `exclude` overrides Jekyll defaults, so keep `vendor` and cache dirs here.
exclude:        [Gemfile, Gemfile.lock, README.md, vendor, vendor/bundle, .bundle, .jekyll-cache, .sass-cache, node_modules]
# whitelist of files/folders to always publish (these would be excluded because of prefix)
include:        [_assets]

theme: null  # not using any pre-built theme
# ask for as much checking as possible
liquid:
  error_mode:       strict
  strict_front_matter: true
# strict_variables:   true    # JDZ: not compatible with jekyll-sitemap, sigh
  strict_filters:     true
lang:               en-US

remote_theme: eecs485staff/primer-spec@36235863da4c1e6225a27fa3d398209a16d63d77
plugins:        [jekyll-remote-theme,jekyll-optional-front-matter,jekyll-readme-index,jekyll-relative-links,jekyll-default-layout,jemoji,jekyll-sitemap]
